upcod

diff --git a/ferramentascodes b/ferramentascodes
--- a/ferramentascodes
+++ b/ferramentascodes
@@ -755,6 +755,72 @@ paybrute () {
 chmod +x ./paysnd.sh
 ./paysnd.sh
 }
+#LISTA PORTAS
+mportas () {
+unset portas
+portas_var=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
+while read port; do
+var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
+[[ "$(echo -e $portas|grep "$var1 $var2")" ]] || portas+="$var1 $var2\n"
+done <<< "$portas_var"
+i=1
+echo -e "$portas"
+}
+ssl_puente () {
+[[ $(mportas|grep stunnel4|head -1) ]] && {
+echo -e "$barra"
+echo -e " \033[1;33m Deteniendo SSL/TLS Bridg"
+echo -e "$barra"
+fun_bar "apt-get purge stunnel4 -y"
+echo -e "$barra"
+echo -e "\033[1;33m Detenido con éxito"
+echo -e "$barra"
+return 0
+}
+echo -e "$barra"
+echo -e " \033[1;36m Instalador SSL/TLS Bridg"
+msg -bar
+echo -e "$barra"
+echo -e "\033[1;36mSelecione un puerto de Redirecionamento Interno"
+echo -e "\033[1;33mEs decir, un puerto en su servidor para SSL/TLS Bridg"
+echo -e "$barra"
+         while true; do
+         echo -ne "\033[1;37m"
+         read -p " Puerto Interno: " portx
+         if [[ ! -z $portx ]]; then
+             if [[ $(echo $portx|grep [0-9]) ]]; then
+                [[ $(mportas|grep $portx|head -1) ]] && break || echo -e "\033[1;31m $(source trans -b pt:${id} "Porta Invalida")"
+             fi
+         fi
+         done
+echo -e "$barra"
+DPORT="$(mportas|grep $portx|awk '{print $2}'|head -1)"
+echo -e "\033[1;35m Ahora necesitamos saber en qué puerto instalarás SSL/TLS Bridg"
+echo -e "$barra"
+    while true; do
+    read -p " Puerto SSL/TLS Bridg: " SSLPORT
+    [[ $(mportas|grep $SSLPORT) ]] || break
+    echo -e "\033[1;33m $(source trans -b es:${id} "El puerto seleccionado ya se encuentra en uso")"
+    unset SSLPORT
+	echo -e "$barra"
+	return 0
+    done
+echo -e "$barra"
+echo -e "\033[1;33m Instalando SSL/TLS Bridg"
+echo -e "$barra"
+fun_bar "apt-get install stunnel4 -y"
+echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:${DPORT}\naccept = ${SSLPORT}" > /etc/stunnel/stunnel.conf
+openssl genrsa -out key.pem 2048 > /dev/null 2>&1
+(echo br; echo br; echo uss; echo speed; echo adm; echo lulseck; echo @eddyjhoel)|openssl req -new -x509 -key key.pem -out cert.pem -days 1095 > /dev/null 2>&1
+cat key.pem cert.pem >> /etc/stunnel/stunnel.pem
+sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
+service stunnel4 restart > /dev/null 2>&1
+echo -e "$barra"
+echo -e "\033[1;33m INSTALADO CON ÉXITO"
+echo -e "$msg"
+echo -e "\033[1;37m Si deseas desinstalar, recuerda volver a seleccionar la misma herramienta"
+return 0
+}
 
 function_16 () {
 tmp_arq="/tmp/arq-tmp"
@@ -893,6 +959,7 @@ source <(curl -sSL https://raw.githubusercontent.com/EddyJhoel/Lulseck/master/On
 [[ "$1" = "16" ]] && function_16
 [[ "$1" = "17" ]] && function_17
 [[ "$1" = "20" ]] && namsobin
+[[ "$1" = "21" ]] && ssl_puente
 ####_Eliminar_Tmps_####
 [[ -e $_tmp ]] && rm $_tmp
 [[ -e $_tmp2 ]] && rm $_tmp2
